// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpeC2sSBdyMgjP-w2X2W4ZKLnTf496XLk',
    appId: '1:270082601373:android:f418fe666afa01aef7bf74',
    messagingSenderId: '270082601373',
    projectId: 'test-instagram-f97c7',
    storageBucket: 'test-instagram-f97c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB1cmMO8KnA0dJJ3UEmU3ZkncdNn8Ehi8',
    appId: '1:270082601373:ios:f869fdfb5bb7ec6ef7bf74',
    messagingSenderId: '270082601373',
    projectId: 'test-instagram-f97c7',
    storageBucket: 'test-instagram-f97c7.appspot.com',
    iosClientId:
        '270082601373-fjikb002eebak8ggheg5kh4m3500al95.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhsoftInstagramClone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCFYrLe8nQwCmWljC9a-GXh0IObNzvh3CA",
    authDomain: "test-instagram-f97c7.firebaseapp.com",
    projectId: "test-instagram-f97c7",
    storageBucket: "test-instagram-f97c7.appspot.com",
    messagingSenderId: "270082601373",
    appId: "1:270082601373:web:2dc6f011b49b0b93f7bf74",
  );
}
