// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDML8kbIDe9fWYTm3lYR97c76dzumpW84',
    appId: '1:352181007736:android:a75ea7ccfe63c30a7cc48d',
    messagingSenderId: '352181007736',
    projectId: 'bhsoft-demo-login',
    storageBucket: 'bhsoft-demo-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdkmnW8mwy-943wsYNuUzAPzfDMWq8Y2c',
    appId: '1:352181007736:ios:74e12a2ae4a99b657cc48d',
    messagingSenderId: '352181007736',
    projectId: 'bhsoft-demo-login',
    storageBucket: 'bhsoft-demo-login.appspot.com',
    androidClientId:
        '352181007736-fg3h1lo2ijmf7ccemhn7qq07b3fi281u.apps.googleusercontent.com',
    iosClientId:
        '352181007736-qa83ua4lljbqclgog0lh4s94gdmpg59p.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.flutter.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBISvsCIQ6eJEPSzfocIZy1vgHG0ZhehAw",
      authDomain: "bhsoft-demo-login.firebaseapp.com",
      projectId: "bhsoft-demo-login",
      storageBucket: "bhsoft-demo-login.appspot.com",
      messagingSenderId: "352181007736",
      appId: "1:352181007736:web:67818b80d200e59d7cc48d");
}
